# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AWSMobileHubDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  $awsVersion = '~> 2.9.0'
  pod 'AWSCore', $awsVersion
  pod 'AWSCognitoIdentityProvider', $awsVersion
  pod 'MBProgressHUD'
  pod 'ReachabilitySwift'
  pod 'IQKeyboardManagerSwift'
  pod 'AWSPinpoint'
  pod 'AWSMobileClient'
  
  # Pods for AWSMobileHubDemo

  target 'AWSMobileHubDemoTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
